apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reader
  namespace: test-istio

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-istio
  name: config-reader-role
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["get", "watch", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-reader-roleBinding
  namespace: test-istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-reader-role
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: test-istio